# Generated by Django 4.2.7 on 2023-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
